# Vue 2 Table
Sortable, searchable/filterable, and paginated.

Please note, that I'm not providing this as a catch-all component, this is merely an example, to show how to create such a component. If you would like to contribute or help to improve this, please do feel free to submit a pull request, or new issue.

## Dependencies
To get the most out of this example, you will need...
* [Node.js and npm](https://www.npmjs.com/get-npm)
* [Gulp.js](https://gulpjs.com/)

## Installation
Everything is already pre-compiled for you to look at the demo code straight away, but if you wish to edit and play with it, you will need to follow these steps...

1. Clone the repo into a directory
1. Via the command line, install the node plugins by running the command `npm install`

You're now setup, and can either run the `gulp` command to rebuild the css, or use `gulp sass:watch` to run in the background, watching for changes in the sass files.

## Attribution

The sample data was generated by the excellent tool [Mockaroo](https://www.mockaroo.com).
